services:
  backendff:
    build:
      context: .
      dockerfile: apps/backendff/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app_network
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backendff
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - BACKENDFF_URL=http://backendff:3001/api
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
